import { Metadata } from "next";
import './styles/index.scss'
import { TheHeader } from "@/components/TheHeader";
import s from './global.module.scss'
import {SideBar} from "@/components/sideBar/SideBar";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
       <div className={s.side}><SideBar /></div>
        <main className={s.main}  >{children}</main>
      </body>
    </html>
  );
}
